#! /bin/bash

for file in $(ls *.h)
do
        ci  $file
done
for file in $(ls *.c)
do
        ci  $file
done
for file in $(ls *.h,v)
do
        co  $file
done
for file in $(ls *.c,v)
do
        co  $file
done
if ( make )
then
        echo "____SUCCESS____"
        read -n1 -p "do you want to run (y/n)" response
        echo
        if [ $response = 'y' ]
        then
                ./linklist
#               read 
        else
                echo "make fail"


        fi
fi
                read -n1 -p "Do you want to edit further ? (y/n) " response

                if [ $response = 'y' ]
                then
                        for file in $(ls *.h,v)
                        do
                        co -l $file
                        done
                        for file in $(ls *.c,v)
                        do
                                co -l $file
                        done
                fi

